<?php
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ApiController\Apiadministrator;
use App\Http\Controllers\ApiController\Apisettings;
use App\Http\Controllers\ApiController\Apidoctorsdistributions;
use App\Http\Controllers\ApiController\Apievaluations;
use App\Http\Controllers\AuthController;

/*
Api Generated by Generatesystems.com Application
*/
Route::post("register", [AuthController::class,"register"]);
Route::post("login", [AuthController::class,"login"]);


/********** Start Authenticated links **********/
 // API PROCCESS 20000004
Route::middleware("auth:sanctum")->group(function () {

Route::get("profile", [AuthController::class,"profile"]);
Route::post("logout", [AuthController::class,"logout"]);
Route::post("updateUserData", [AuthController::class,"updateUserData"]);


/********Start Api (users) **********/
Route::post("administrator_users_insert", [Apiadministrator::class,"administrator_users_insert"]);
Route::get("administrator_users_viewAll", [Apiadministrator::class,"administrator_users_viewAll"]);
Route::delete("administrator_users_delete", [Apiadministrator::class,"administrator_users_delete"]);
Route::put("administrator_users_update", [Apiadministrator::class,"administrator_users_update"]);
/********End Api (users) **********/


/********Start Api (tbl_users_type) **********/
Route::post("administrator_tbl_users_type_insert", [Apiadministrator::class,"administrator_tbl_users_type_insert"]);
Route::get("administrator_tbl_users_type_viewAll", [Apiadministrator::class,"administrator_tbl_users_type_viewAll"]);
Route::delete("administrator_tbl_users_type_delete", [Apiadministrator::class,"administrator_tbl_users_type_delete"]);
Route::put("administrator_tbl_users_type_update", [Apiadministrator::class,"administrator_tbl_users_type_update"]);
/********End Api (tbl_users_type) **********/


/********Start Api (genders) **********/
Route::post("settings_genders_insert", [Apisettings::class,"settings_genders_insert"]);
Route::get("settings_genders_viewAll", [Apisettings::class,"settings_genders_viewAll"]);
Route::delete("settings_genders_delete", [Apisettings::class,"settings_genders_delete"]);
Route::put("settings_genders_update", [Apisettings::class,"settings_genders_update"]);
/********End Api (genders) **********/


/********Start Api (status) **********/
Route::post("settings_status_insert", [Apisettings::class,"settings_status_insert"]);
Route::get("settings_status_viewAll", [Apisettings::class,"settings_status_viewAll"]);
Route::delete("settings_status_delete", [Apisettings::class,"settings_status_delete"]);
Route::put("settings_status_update", [Apisettings::class,"settings_status_update"]);
/********End Api (status) **********/


/********Start Api (university_major) **********/
Route::post("settings_university_major_insert", [Apisettings::class,"settings_university_major_insert"]);
Route::get("settings_university_major_viewAll", [Apisettings::class,"settings_university_major_viewAll"]);
Route::delete("settings_university_major_delete", [Apisettings::class,"settings_university_major_delete"]);
Route::put("settings_university_major_update", [Apisettings::class,"settings_university_major_update"]);
/********End Api (university_major) **********/


/********Start Api (city) **********/
Route::post("settings_city_insert", [Apisettings::class,"settings_city_insert"]);
Route::get("settings_city_viewAll", [Apisettings::class,"settings_city_viewAll"]);
Route::delete("settings_city_delete", [Apisettings::class,"settings_city_delete"]);
Route::put("settings_city_update", [Apisettings::class,"settings_city_update"]);
/********End Api (city) **********/


/********Start Api (hospitals) **********/
Route::post("settings_hospitals_insert", [Apisettings::class,"settings_hospitals_insert"]);
Route::get("settings_hospitals_viewAll", [Apisettings::class,"settings_hospitals_viewAll"]);
Route::delete("settings_hospitals_delete", [Apisettings::class,"settings_hospitals_delete"]);
Route::put("settings_hospitals_update", [Apisettings::class,"settings_hospitals_update"]);
/********End Api (hospitals) **********/


/********Start Api (specialties) **********/
Route::post("settings_specialties_insert", [Apisettings::class,"settings_specialties_insert"]);
Route::get("settings_specialties_viewAll", [Apisettings::class,"settings_specialties_viewAll"]);
Route::delete("settings_specialties_delete", [Apisettings::class,"settings_specialties_delete"]);
Route::put("settings_specialties_update", [Apisettings::class,"settings_specialties_update"]);
/********End Api (specialties) **********/


/********Start Api (hospitals_has_specialties) **********/
Route::post("settings_hospitals_has_specialties_insert", [Apisettings::class,"settings_hospitals_has_specialties_insert"]);
Route::get("settings_hospitals_has_specialties_viewAll", [Apisettings::class,"settings_hospitals_has_specialties_viewAll"]);
Route::delete("settings_hospitals_has_specialties_delete", [Apisettings::class,"settings_hospitals_has_specialties_delete"]);
Route::put("settings_hospitals_has_specialties_update", [Apisettings::class,"settings_hospitals_has_specialties_update"]);
/********End Api (hospitals_has_specialties) **********/


/********Start Api (distributions) **********/
Route::post("doctorsdistributions_distributions_insert", [Apidoctorsdistributions::class,"doctorsdistributions_distributions_insert"]);
Route::get("doctorsdistributions_distributions_viewAll", [Apidoctorsdistributions::class,"doctorsdistributions_distributions_viewAll"]);
Route::delete("doctorsdistributions_distributions_delete", [Apidoctorsdistributions::class,"doctorsdistributions_distributions_delete"]);
Route::put("doctorsdistributions_distributions_update", [Apidoctorsdistributions::class,"doctorsdistributions_distributions_update"]);
/********End Api (distributions) **********/


/********Start Api (clinical_setting) **********/
Route::post("settings_clinical_setting_insert", [Apisettings::class,"settings_clinical_setting_insert"]);
Route::get("settings_clinical_setting_viewAll", [Apisettings::class,"settings_clinical_setting_viewAll"]);
Route::delete("settings_clinical_setting_delete", [Apisettings::class,"settings_clinical_setting_delete"]);
Route::put("settings_clinical_setting_update", [Apisettings::class,"settings_clinical_setting_update"]);
/********End Api (clinical_setting) **********/


/********Start Api (monthly_evaluation_forms) **********/
Route::post("settings_monthly_evaluation_forms_insert", [Apisettings::class,"settings_monthly_evaluation_forms_insert"]);
Route::get("settings_monthly_evaluation_forms_viewAll", [Apisettings::class,"settings_monthly_evaluation_forms_viewAll"]);
Route::delete("settings_monthly_evaluation_forms_delete", [Apisettings::class,"settings_monthly_evaluation_forms_delete"]);
Route::put("settings_monthly_evaluation_forms_update", [Apisettings::class,"settings_monthly_evaluation_forms_update"]);
/********End Api (monthly_evaluation_forms) **********/


/********Start Api (assessment_criteria) **********/
Route::post("settings_assessment_criteria_insert", [Apisettings::class,"settings_assessment_criteria_insert"]);
Route::get("settings_assessment_criteria_viewAll", [Apisettings::class,"settings_assessment_criteria_viewAll"]);
Route::delete("settings_assessment_criteria_delete", [Apisettings::class,"settings_assessment_criteria_delete"]);
Route::put("settings_assessment_criteria_update", [Apisettings::class,"settings_assessment_criteria_update"]);
/********End Api (assessment_criteria) **********/


/********Start Api (monthly_evaluations) **********/
Route::post("evaluations_monthly_evaluations_insert", [Apievaluations::class,"evaluations_monthly_evaluations_insert"]);
Route::get("evaluations_monthly_evaluations_viewAll", [Apievaluations::class,"evaluations_monthly_evaluations_viewAll"]);
Route::delete("evaluations_monthly_evaluations_delete", [Apievaluations::class,"evaluations_monthly_evaluations_delete"]);
Route::put("evaluations_monthly_evaluations_update", [Apievaluations::class,"evaluations_monthly_evaluations_update"]);
/********End Api (monthly_evaluations) **********/


/********Start Api (monthly_evaluations_details) **********/
Route::post("evaluations_monthly_evaluations_details_insert", [Apievaluations::class,"evaluations_monthly_evaluations_details_insert"]);
Route::get("evaluations_monthly_evaluations_details_viewAll", [Apievaluations::class,"evaluations_monthly_evaluations_details_viewAll"]);
Route::delete("evaluations_monthly_evaluations_details_delete", [Apievaluations::class,"evaluations_monthly_evaluations_details_delete"]);
Route::put("evaluations_monthly_evaluations_details_update", [Apievaluations::class,"evaluations_monthly_evaluations_details_update"]);
/********End Api (monthly_evaluations_details) **********/


  
  
  
  
  
  
  
  
  
  
  }); 
