<?php
namespace App\Http\Controllers\ApiController;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Response;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\SystemController\Delete;
use App\Http\Controllers\AdminController\UserAuthController;
use Illuminate\Support\Facades\Storage;

use App\Models\Admin\users_model as users;
use App\Models\Admin\tbl_users_type_model as tbl_users_type;
 
 
 /******************************************************/
 /******************************************************/
 /**********************Generated By *******************/
 /************* https://generatesystems.com ************/
 /******************************************************/
 /******************************************************/
 
 
class Apiadministrator  extends Controller{
/*************Start Table users Api******************/
public function administrator_users_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table users
 Parameters{
 name
 email
 profile_photo_path
 tbl_users_type_id
 phone
 genders_id
 city_id
 specialties_id
 hospitals_id
 }
*/
   $request->validate(users::rules());;
   $data=array(); 
   $data["name"]= $request->input()["name"] ; 
   $data["email"]= $request->input()["email"] ; 
   $data["tbl_users_type_id"]= $request->input()["tbl_users_type_id"] ; 
   $data["phone"]= $request->input()["phone"] ; 
   $data["genders_id"]= $request->input()["genders_id"] ; 
   $data["city_id"]= $request->input()["city_id"] ; 
   $data["specialties_id"]= $request->input()["specialties_id"] ; 
   $data["hospitals_id"]= $request->input()["hospitals_id"] ; 
if ($request->hasFile("profile_photo_path")) {
        $file = $request->file("profile_photo_path");
        $path  = $file->store("documents",["disk" => "uploads"]);
        $data["profile_photo_path"]= $path ; 
    }
  $data["password"]=  Hash::make(123456)  ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = users::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function administrator_users_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table users
 Parameters{
 name
 email
 profile_photo_path
 tbl_users_type_id
 phone
 genders_id
 city_id
 specialties_id
 hospitals_id
 }
*/
  // proccess 10000002
    try {
    $users = users::findOrFail($request->input()["id"]);
    //$request->validate(users::rules());;
    $data = array();
    if ($request->exists("name")) {
      $data["name"]= $request->input()["name"] ; 
    }
    if ($request->exists("email")) {
      $data["email"]= $request->input()["email"] ; 
    }
    if ($request->exists("tbl_users_type_id")) {
      $data["tbl_users_type_id"]= $request->input()["tbl_users_type_id"] ; 
    }
    if ($request->exists("phone")) {
      $data["phone"]= $request->input()["phone"] ; 
    }
    if ($request->exists("genders_id")) {
      $data["genders_id"]= $request->input()["genders_id"] ; 
    }
    if ($request->exists("city_id")) {
      $data["city_id"]= $request->input()["city_id"] ; 
    }
    if ($request->exists("specialties_id")) {
      $data["specialties_id"]= $request->input()["specialties_id"] ; 
    }
    if ($request->exists("hospitals_id")) {
      $data["hospitals_id"]= $request->input()["hospitals_id"] ; 
    }
    if ($request->hasFile("profile_photo_path")) {
    // remove old photo from Storage
     if( $users->profile_photo_path != ""){
      Storage::disk("uploads")->delete($users->profile_photo_path);
     }
      $file = $request->file("profile_photo_path");
      $path  = $file->store("documents",["disk" => "uploads"]);
      $data["profile_photo_path"]= $path ; 
    } 
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $users->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function administrator_users_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = users::select(    
"users.active_status_id AS active_status_id",
"users.tbl_users_type_id AS tbl_users_type_id",
                  "users.id   AS  id",
                  "users.name   AS  name",
                  "users.email   AS  email",
                  "users.profile_photo_path   AS  profile_photo_path",
                  DB::raw("concat('$hostUrl',users.profile_photo_path)   AS  profile_photo_path_url"),
                  "tbl_users_type.name    AS  tbl_users_type_id_name",
                  "users.tbl_users_type_id   AS  tbl_users_type_id",
                  "users.phone   AS  phone",
                  "genders.name_$lang    AS  genders_id_name_en",
                  "users.genders_id   AS  genders_id",
                  "city.name_$lang    AS  city_id_name_en",
                  "users.city_id   AS  city_id",
                  "specialties.name_$lang    AS  specialties_id_name_en",
                  "users.specialties_id   AS  specialties_id",
                  "hospitals.name    AS  hospitals_id_name",
                  "users.hospitals_id   AS  hospitals_id"
                   )
                 ->join ( 'tbl_users_type as tbl_users_type' ,'users.tbl_users_type_id', '=', 'tbl_users_type.id'  )
                 ->leftjoin ( 'genders as genders' ,'users.genders_id', '=', 'genders.id'  )
                 ->leftjoin ( 'city as city' ,'users.city_id', '=', 'city.id'  )
                 ->leftjoin ( 'specialties as specialties' ,'users.specialties_id', '=', 'specialties.id'  )
                 ->leftjoin ( 'hospitals as hospitals' ,'users.hospitals_id', '=', 'hospitals.id'  )
                   ;

  if($request->exists("id")){  
     $data=$data->where("users.id","=" ,$request->input("id"));
  }
  if($request->exists("name")){  
     $data=$data->where("users.name","=" ,$request->input("name"));
  }
  if($request->exists("email")){  
     $data=$data->where("users.email","=" ,$request->input("email"));
  }
  if($request->exists("profile_photo_path")){  
     $data=$data->where("users.profile_photo_path","=" ,$request->input("profile_photo_path"));
  }
  if($request->exists("tbl_users_type_id")){  
     $data=$data->where("users.tbl_users_type_id","=" ,$request->input("tbl_users_type_id"));
  }
  if($request->exists("phone")){  
     $data=$data->where("users.phone","=" ,$request->input("phone"));
  }
  if($request->exists("genders_id")){  
     $data=$data->where("users.genders_id","=" ,$request->input("genders_id"));
  }
  if($request->exists("city_id")){  
     $data=$data->where("users.city_id","=" ,$request->input("city_id"));
  }
  if($request->exists("specialties_id")){  
     $data=$data->where("users.specialties_id","=" ,$request->input("specialties_id"));
  }
  if($request->exists("hospitals_id")){  
     $data=$data->where("users.hospitals_id","=" ,$request->input("hospitals_id"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function administrator_users_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table users
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="users";
 $id_name =  "users_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End users*****************************/

/*************Start Table tbl_users_type Api******************/
public function administrator_tbl_users_type_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table tbl_users_type
 Parameters{
 name
 }
*/
   $request->validate(tbl_users_type::rules());;
   $data=array(); 
   $data["name"]=  $request->input()["name"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = tbl_users_type::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function administrator_tbl_users_type_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table tbl_users_type
 Parameters{
 name
 }
*/
  // proccess 10000002
    try {
    $tbl_users_type = tbl_users_type::findOrFail($request->input()["id"]);
    //$request->validate(tbl_users_type::rules());;
    $data = array();
    if ($request->exists("name")) {
      $data["name"]= $request->input()["name"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $tbl_users_type->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function administrator_tbl_users_type_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = tbl_users_type::select(    
                  "tbl_users_type.id   AS  id",
                  "tbl_users_type.name   AS  name"
                   )
                   ;

  if($request->exists("id")){  
     $data=$data->where("tbl_users_type.id","=" ,$request->input("id"));
  }
  if($request->exists("name")){  
     $data=$data->where("tbl_users_type.name","=" ,$request->input("name"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function administrator_tbl_users_type_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table tbl_users_type
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="tbl_users_type";
 $id_name =  "tbl_users_type_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End tbl_users_type*****************************/

}
