<?php
namespace App\Http\Controllers\ApiController;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Response;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\SystemController\Delete;
use App\Http\Controllers\AdminController\UserAuthController;
use Illuminate\Support\Facades\Storage;

use App\Models\Admin\distributions_model as distributions;
 
 
 /******************************************************/
 /******************************************************/
 /**********************Generated By *******************/
 /************* https://generatesystems.com ************/
 /******************************************************/
 /******************************************************/
 
 
class Apidoctorsdistributions  extends Controller{
/*************Start Table distributions Api******************/
public function doctorsdistributions_distributions_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table distributions
 Parameters{
 users_id
 hospitals_id
 hospitals_has_specialties_id
 status_id
 }
*/
   $request->validate(distributions::rules());;
   $data=array(); 
   $data["users_id"]=  $request->input()["users_id"] ; 
   $data["hospitals_id"]=  $request->input()["hospitals_id"] ; 
   $data["hospitals_has_specialties_id"]=  $request->input()["hospitals_has_specialties_id"] ; 
   $data["status_id"]=  $request->input()["status_id"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = distributions::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function doctorsdistributions_distributions_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table distributions
 Parameters{
 users_id
 hospitals_id
 hospitals_has_specialties_id
 status_id
 }
*/
  // proccess 10000002
    try {
    $distributions = distributions::findOrFail($request->input()["id"]);
    //$request->validate(distributions::rules());;
    $data = array();
    if ($request->exists("users_id")) {
      $data["users_id"]= $request->input()["users_id"] ; 
    }
    if ($request->exists("hospitals_id")) {
      $data["hospitals_id"]= $request->input()["hospitals_id"] ; 
    }
    if ($request->exists("hospitals_has_specialties_id")) {
      $data["hospitals_has_specialties_id"]= $request->input()["hospitals_has_specialties_id"] ; 
    }
    if ($request->exists("status_id")) {
      $data["status_id"]= $request->input()["status_id"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $distributions->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function doctorsdistributions_distributions_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = distributions::select(    
                  "distributions.id   AS  id",
                  "users.name    AS  users_id_name",
                  "distributions.users_id   AS  users_id",
                  "hospitals.name    AS  hospitals_id_name",
                  "distributions.hospitals_id   AS  hospitals_id",
                  "hospitals_has_specialties.specialties_id    AS  hospitals_has_specialties_id_specialties_id",
                  "distributions.hospitals_has_specialties_id   AS  hospitals_has_specialties_id",
                  "status.name_$lang    AS  status_id_name_en",
                  "distributions.status_id   AS  status_id"
                   )
                 ->join ( 'users as users' ,'distributions.users_id', '=', 'users.id'  )
                 ->join ( 'hospitals as hospitals' ,'distributions.hospitals_id', '=', 'hospitals.id'  )
                 ->join ( 'hospitals_has_specialties as hospitals_has_specialties' ,'distributions.hospitals_has_specialties_id', '=', 'hospitals_has_specialties.id'  )
                 ->join ( 'status as status' ,'distributions.status_id', '=', 'status.id'  )
                   ;

  if($request->exists("id")){  
     $data=$data->where("distributions.id","=" ,$request->input("id"));
  }
  if($request->exists("users_id")){  
     $data=$data->where("distributions.users_id","=" ,$request->input("users_id"));
  }
  if($request->exists("hospitals_id")){  
     $data=$data->where("distributions.hospitals_id","=" ,$request->input("hospitals_id"));
  }
  if($request->exists("hospitals_has_specialties_id")){  
     $data=$data->where("distributions.hospitals_has_specialties_id","=" ,$request->input("hospitals_has_specialties_id"));
  }
  if($request->exists("status_id")){  
     $data=$data->where("distributions.status_id","=" ,$request->input("status_id"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function doctorsdistributions_distributions_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table distributions
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="distributions";
 $id_name =  "distributions_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End distributions*****************************/

}
