<?php
namespace App\Http\Controllers\ApiController;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Response;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\SystemController\Delete;
use App\Http\Controllers\AdminController\UserAuthController;
use Illuminate\Support\Facades\Storage;

use App\Models\Admin\employees_model as employees;
 
 
 /******************************************************/
 /******************************************************/
 /**********************Generated By *******************/
 /************* https://generatesystems.com ************/
 /******************************************************/
 /******************************************************/
 
 
class Apiemps  extends Controller{
/*************Start Table employees Api******************/
public function emps_employees_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table employees
 Parameters{
 emp_name
 country_id
 city_id
 date_of_join
 date_of_birth
 salary
 }
*/
   $request->validate(employees::rules());;
   $data=array(); 
   $data["emp_name"]=  $request->input()["emp_name"] ; 
   $data["country_id"]=  $request->input()["country_id"] ; 
   $data["city_id"]=  $request->input()["city_id"] ; 
   $data["date_of_join"]=  $request->input()["date_of_join"] ; 
   $data["date_of_birth"]=  $request->input()["date_of_birth"] ; 
   $data["salary"]=  $request->input()["salary"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = employees::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function emps_employees_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table employees
 Parameters{
 emp_name
 country_id
 city_id
 date_of_join
 date_of_birth
 salary
 }
*/
  // proccess 10000002
    try {
    $employees = employees::findOrFail($request->input()["id"]);
    //$request->validate(employees::rules());;
    $data = array();
    if ($request->exists("emp_name")) {
      $data["emp_name"]= $request->input()["emp_name"] ; 
    }
    if ($request->exists("country_id")) {
      $data["country_id"]= $request->input()["country_id"] ; 
    }
    if ($request->exists("city_id")) {
      $data["city_id"]= $request->input()["city_id"] ; 
    }
    if ($request->exists("date_of_join")) {
      $data["date_of_join"]= $request->input()["date_of_join"] ; 
    }
    if ($request->exists("date_of_birth")) {
      $data["date_of_birth"]= $request->input()["date_of_birth"] ; 
    }
    if ($request->exists("salary")) {
      $data["salary"]= $request->input()["salary"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $employees->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function emps_employees_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = employees::select(    
                  "employees.id   AS  id",
                  "employees.emp_name   AS  emp_name",
                  "country.name_$lang    AS  country_id_name_en",
                  "employees.country_id   AS  country_id",
                  "city.name_$lang    AS  city_id_name_en",
                  "employees.city_id   AS  city_id",
                  "employees.date_of_join   AS  date_of_join",
                  "employees.date_of_birth   AS  date_of_birth",
                  "employees.salary   AS  salary"
                   )
                 ->join ( 'country as country' ,'employees.country_id', '=', 'country.id'  )
                 ->join ( 'city as city' ,'employees.city_id', '=', 'city.id'  )
                   ;

  if($request->exists("id")){  
     $data=$data->where("employees.id","=" ,$request->input("id"));
  }
  if($request->exists("emp_name")){  
     $data=$data->where("employees.emp_name","=" ,$request->input("emp_name"));
  }
  if($request->exists("country_id")){  
     $data=$data->where("employees.country_id","=" ,$request->input("country_id"));
  }
  if($request->exists("city_id")){  
     $data=$data->where("employees.city_id","=" ,$request->input("city_id"));
  }
  if($request->exists("date_of_join")){  
     $data=$data->where("employees.date_of_join","=" ,$request->input("date_of_join"));
  }
  if($request->exists("date_of_birth")){  
     $data=$data->where("employees.date_of_birth","=" ,$request->input("date_of_birth"));
  }
  if($request->exists("salary")){  
     $data=$data->where("employees.salary","=" ,$request->input("salary"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function emps_employees_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table employees
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="employees";
 $id_name =  "employees_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End employees*****************************/

}
