<?php
namespace App\Http\Controllers\ApiController;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Response;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\SystemController\Delete;
use App\Http\Controllers\AdminController\UserAuthController;
use Illuminate\Support\Facades\Storage;

use App\Models\Admin\monthly_evaluations_model as monthly_evaluations;
use App\Models\Admin\monthly_evaluations_details_model as monthly_evaluations_details;
 
 
 /******************************************************/
 /******************************************************/
 /**********************Generated By *******************/
 /************* https://generatesystems.com ************/
 /******************************************************/
 /******************************************************/
 
 
class Apievaluations  extends Controller{
/*************Start Table monthly_evaluations Api******************/
public function evaluations_monthly_evaluations_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table monthly_evaluations
 Parameters{
 users_id
 hospitals_has_specialties_id
 monthly_evaluation_forms_id
 }
*/
   $request->validate(monthly_evaluations::rules());;
   $data=array(); 
   $data["users_id"]=  $request->input()["users_id"] ; 
   $data["hospitals_has_specialties_id"]=  $request->input()["hospitals_has_specialties_id"] ; 
   $data["monthly_evaluation_forms_id"]=  $request->input()["monthly_evaluation_forms_id"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = monthly_evaluations::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function evaluations_monthly_evaluations_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table monthly_evaluations
 Parameters{
 users_id
 hospitals_has_specialties_id
 monthly_evaluation_forms_id
 }
*/
  // proccess 10000002
    try {
    $monthly_evaluations = monthly_evaluations::findOrFail($request->input()["id"]);
    //$request->validate(monthly_evaluations::rules());;
    $data = array();
    if ($request->exists("users_id")) {
      $data["users_id"]= $request->input()["users_id"] ; 
    }
    if ($request->exists("hospitals_has_specialties_id")) {
      $data["hospitals_has_specialties_id"]= $request->input()["hospitals_has_specialties_id"] ; 
    }
    if ($request->exists("monthly_evaluation_forms_id")) {
      $data["monthly_evaluation_forms_id"]= $request->input()["monthly_evaluation_forms_id"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $monthly_evaluations->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function evaluations_monthly_evaluations_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = monthly_evaluations::select(    
                  "monthly_evaluations.id   AS  id",
                  "users.name    AS  users_id_name",
                  "monthly_evaluations.users_id   AS  users_id",
                  "hospitals_has_specialties.id    AS  hospitals_has_specialties_id_id",
                  "monthly_evaluations.hospitals_has_specialties_id   AS  hospitals_has_specialties_id",
                  "monthly_evaluation_forms.name    AS  monthly_evaluation_forms_id_name",
                  "monthly_evaluations.monthly_evaluation_forms_id   AS  monthly_evaluation_forms_id"
                   )
                 ->join ( 'users as users' ,'monthly_evaluations.users_id', '=', 'users.id'  )
                 ->join ( 'hospitals_has_specialties as hospitals_has_specialties' ,'monthly_evaluations.hospitals_has_specialties_id', '=', 'hospitals_has_specialties.id'  )
                 ->join ( 'monthly_evaluation_forms as monthly_evaluation_forms' ,'monthly_evaluations.monthly_evaluation_forms_id', '=', 'monthly_evaluation_forms.id'  )
                   ;

  if($request->exists("id")){  
     $data=$data->where("monthly_evaluations.id","=" ,$request->input("id"));
  }
  if($request->exists("users_id")){  
     $data=$data->where("monthly_evaluations.users_id","=" ,$request->input("users_id"));
  }
  if($request->exists("hospitals_has_specialties_id")){  
     $data=$data->where("monthly_evaluations.hospitals_has_specialties_id","=" ,$request->input("hospitals_has_specialties_id"));
  }
  if($request->exists("monthly_evaluation_forms_id")){  
     $data=$data->where("monthly_evaluations.monthly_evaluation_forms_id","=" ,$request->input("monthly_evaluation_forms_id"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function evaluations_monthly_evaluations_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table monthly_evaluations
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="monthly_evaluations";
 $id_name =  "monthly_evaluations_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End monthly_evaluations*****************************/

/*************Start Table monthly_evaluations_details Api******************/
public function evaluations_monthly_evaluations_details_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table monthly_evaluations_details
 Parameters{
 monthly_evaluations_id
 assessment_criteria_id
 n_a
 below_standard
 meets_standard
 above_standard
 feedback_discussion
 feedback
 aspects
 suggested
 able_perform_procedure
 unable_perform_procedure
 trained_and_competent
 able_perform_procedure_limited
 competent_perform_procedure_unsupervised
 agree_action_plan
 }
*/
   $request->validate(monthly_evaluations_details::rules());;
   $data=array(); 
   $data["monthly_evaluations_id"]=  $request->input()["monthly_evaluations_id"] ; 
   $data["assessment_criteria_id"]=  $request->input()["assessment_criteria_id"] ; 
   $data["n_a"]=  $request->input()["n_a"] ; 
   $data["below_standard"]=  $request->input()["below_standard"] ; 
   $data["meets_standard"]=  $request->input()["meets_standard"] ; 
   $data["above_standard"]=  $request->input()["above_standard"] ; 
   $data["feedback_discussion"]=  $request->input()["feedback_discussion"] ; 
   $data["feedback"]=  $request->input()["feedback"] ; 
   $data["aspects"]=  $request->input()["aspects"] ; 
   $data["suggested"]=  $request->input()["suggested"] ; 
   $data["able_perform_procedure"]=  $request->input()["able_perform_procedure"] ; 
   $data["unable_perform_procedure"]=  $request->input()["unable_perform_procedure"] ; 
   $data["trained_and_competent"]=  $request->input()["trained_and_competent"] ; 
   $data["able_perform_procedure_limited"]=  $request->input()["able_perform_procedure_limited"] ; 
   $data["competent_perform_procedure_unsupervised"]=  $request->input()["competent_perform_procedure_unsupervised"] ; 
   $data["agree_action_plan"]=  $request->input()["agree_action_plan"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = monthly_evaluations_details::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function evaluations_monthly_evaluations_details_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table monthly_evaluations_details
 Parameters{
 monthly_evaluations_id
 assessment_criteria_id
 n_a
 below_standard
 meets_standard
 above_standard
 feedback_discussion
 feedback
 aspects
 suggested
 able_perform_procedure
 unable_perform_procedure
 trained_and_competent
 able_perform_procedure_limited
 competent_perform_procedure_unsupervised
 agree_action_plan
 }
*/
  // proccess 10000002
    try {
    $monthly_evaluations_details = monthly_evaluations_details::findOrFail($request->input()["id"]);
    //$request->validate(monthly_evaluations_details::rules());;
    $data = array();
    if ($request->exists("monthly_evaluations_id")) {
      $data["monthly_evaluations_id"]= $request->input()["monthly_evaluations_id"] ; 
    }
    if ($request->exists("assessment_criteria_id")) {
      $data["assessment_criteria_id"]= $request->input()["assessment_criteria_id"] ; 
    }
    if ($request->exists("n_a")) {
      $data["n_a"]= $request->input()["n_a"] ; 
    }
    if ($request->exists("below_standard")) {
      $data["below_standard"]= $request->input()["below_standard"] ; 
    }
    if ($request->exists("meets_standard")) {
      $data["meets_standard"]= $request->input()["meets_standard"] ; 
    }
    if ($request->exists("above_standard")) {
      $data["above_standard"]= $request->input()["above_standard"] ; 
    }
    if ($request->exists("feedback_discussion")) {
      $data["feedback_discussion"]= $request->input()["feedback_discussion"] ; 
    }
    if ($request->exists("feedback")) {
      $data["feedback"]= $request->input()["feedback"] ; 
    }
    if ($request->exists("aspects")) {
      $data["aspects"]= $request->input()["aspects"] ; 
    }
    if ($request->exists("suggested")) {
      $data["suggested"]= $request->input()["suggested"] ; 
    }
    if ($request->exists("able_perform_procedure")) {
      $data["able_perform_procedure"]= $request->input()["able_perform_procedure"] ; 
    }
    if ($request->exists("unable_perform_procedure")) {
      $data["unable_perform_procedure"]= $request->input()["unable_perform_procedure"] ; 
    }
    if ($request->exists("trained_and_competent")) {
      $data["trained_and_competent"]= $request->input()["trained_and_competent"] ; 
    }
    if ($request->exists("able_perform_procedure_limited")) {
      $data["able_perform_procedure_limited"]= $request->input()["able_perform_procedure_limited"] ; 
    }
    if ($request->exists("competent_perform_procedure_unsupervised")) {
      $data["competent_perform_procedure_unsupervised"]= $request->input()["competent_perform_procedure_unsupervised"] ; 
    }
    if ($request->exists("agree_action_plan")) {
      $data["agree_action_plan"]= $request->input()["agree_action_plan"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $monthly_evaluations_details->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function evaluations_monthly_evaluations_details_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = monthly_evaluations_details::select(    
                  "monthly_evaluations_details.id   AS  id",
                  "monthly_evaluations.id    AS  monthly_evaluations_id_id",
                  "monthly_evaluations_details.monthly_evaluations_id   AS  monthly_evaluations_id",
                  "assessment_criteria.question    AS  assessment_criteria_id_question",
                  "monthly_evaluations_details.assessment_criteria_id   AS  assessment_criteria_id",
                  "monthly_evaluations_details.n_a   AS  n_a",
                  "monthly_evaluations_details.below_standard   AS  below_standard",
                  "monthly_evaluations_details.meets_standard   AS  meets_standard",
                  "monthly_evaluations_details.above_standard   AS  above_standard",
                  "monthly_evaluations_details.feedback_discussion   AS  feedback_discussion",
                  "monthly_evaluations_details.feedback   AS  feedback",
                  "monthly_evaluations_details.aspects   AS  aspects",
                  "monthly_evaluations_details.suggested   AS  suggested",
                  "monthly_evaluations_details.able_perform_procedure   AS  able_perform_procedure",
                  "monthly_evaluations_details.unable_perform_procedure   AS  unable_perform_procedure",
                  "monthly_evaluations_details.trained_and_competent   AS  trained_and_competent",
                  "monthly_evaluations_details.able_perform_procedure_limited   AS  able_perform_procedure_limited",
                  "monthly_evaluations_details.competent_perform_procedure_unsupervised   AS  competent_perform_procedure_unsupervised",
                  "monthly_evaluations_details.agree_action_plan   AS  agree_action_plan"
                   )
                 ->join ( 'monthly_evaluations as monthly_evaluations' ,'monthly_evaluations_details.monthly_evaluations_id', '=', 'monthly_evaluations.id'  )
                 ->join ( 'assessment_criteria as assessment_criteria' ,'monthly_evaluations_details.assessment_criteria_id', '=', 'assessment_criteria.id'  )
                   ;

  if($request->exists("id")){  
     $data=$data->where("monthly_evaluations_details.id","=" ,$request->input("id"));
  }
  if($request->exists("monthly_evaluations_id")){  
     $data=$data->where("monthly_evaluations_details.monthly_evaluations_id","=" ,$request->input("monthly_evaluations_id"));
  }
  if($request->exists("assessment_criteria_id")){  
     $data=$data->where("monthly_evaluations_details.assessment_criteria_id","=" ,$request->input("assessment_criteria_id"));
  }
  if($request->exists("n_a")){  
     $data=$data->where("monthly_evaluations_details.n_a","=" ,$request->input("n_a"));
  }
  if($request->exists("below_standard")){  
     $data=$data->where("monthly_evaluations_details.below_standard","=" ,$request->input("below_standard"));
  }
  if($request->exists("meets_standard")){  
     $data=$data->where("monthly_evaluations_details.meets_standard","=" ,$request->input("meets_standard"));
  }
  if($request->exists("above_standard")){  
     $data=$data->where("monthly_evaluations_details.above_standard","=" ,$request->input("above_standard"));
  }
  if($request->exists("feedback_discussion")){  
     $data=$data->where("monthly_evaluations_details.feedback_discussion","=" ,$request->input("feedback_discussion"));
  }
  if($request->exists("feedback")){  
     $data=$data->where("monthly_evaluations_details.feedback","=" ,$request->input("feedback"));
  }
  if($request->exists("aspects")){  
     $data=$data->where("monthly_evaluations_details.aspects","=" ,$request->input("aspects"));
  }
  if($request->exists("suggested")){  
     $data=$data->where("monthly_evaluations_details.suggested","=" ,$request->input("suggested"));
  }
  if($request->exists("able_perform_procedure")){  
     $data=$data->where("monthly_evaluations_details.able_perform_procedure","=" ,$request->input("able_perform_procedure"));
  }
  if($request->exists("unable_perform_procedure")){  
     $data=$data->where("monthly_evaluations_details.unable_perform_procedure","=" ,$request->input("unable_perform_procedure"));
  }
  if($request->exists("trained_and_competent")){  
     $data=$data->where("monthly_evaluations_details.trained_and_competent","=" ,$request->input("trained_and_competent"));
  }
  if($request->exists("able_perform_procedure_limited")){  
     $data=$data->where("monthly_evaluations_details.able_perform_procedure_limited","=" ,$request->input("able_perform_procedure_limited"));
  }
  if($request->exists("competent_perform_procedure_unsupervised")){  
     $data=$data->where("monthly_evaluations_details.competent_perform_procedure_unsupervised","=" ,$request->input("competent_perform_procedure_unsupervised"));
  }
  if($request->exists("agree_action_plan")){  
     $data=$data->where("monthly_evaluations_details.agree_action_plan","=" ,$request->input("agree_action_plan"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function evaluations_monthly_evaluations_details_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table monthly_evaluations_details
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="monthly_evaluations_details";
 $id_name =  "monthly_evaluations_details_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End monthly_evaluations_details*****************************/

}
