<?php
namespace App\Http\Controllers\ApiController;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Response;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\SystemController\Delete;
use App\Http\Controllers\AdminController\UserAuthController;
use Illuminate\Support\Facades\Storage;

use App\Models\Admin\genders_model as genders;
use App\Models\Admin\status_model as status;
use App\Models\Admin\university_major_model as university_major;
use App\Models\Admin\city_model as city;
use App\Models\Admin\hospitals_model as hospitals;
use App\Models\Admin\specialties_model as specialties;
use App\Models\Admin\hospitals_has_specialties_model as hospitals_has_specialties;
use App\Models\Admin\clinical_setting_model as clinical_setting;
use App\Models\Admin\monthly_evaluation_forms_model as monthly_evaluation_forms;
use App\Models\Admin\assessment_criteria_model as assessment_criteria;
 
 
 /******************************************************/
 /******************************************************/
 /**********************Generated By *******************/
 /************* https://generatesystems.com ************/
 /******************************************************/
 /******************************************************/
 
 
class Apisettings  extends Controller{
/*************Start Table genders Api******************/
public function settings_genders_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table genders
 Parameters{
 name_en
 name_ar
 }
*/
   $request->validate(genders::rules());;
   $data=array(); 
   $data["name_en"]=  $request->input()["name_en"] ; 
   $data["name_ar"]=  $request->input()["name_ar"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = genders::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function settings_genders_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table genders
 Parameters{
 name_en
 name_ar
 }
*/
  // proccess 10000002
    try {
    $genders = genders::findOrFail($request->input()["id"]);
    //$request->validate(genders::rules());;
    $data = array();
    if ($request->exists("name_en")) {
      $data["name_en"]= $request->input()["name_en"] ; 
    }
    if ($request->exists("name_ar")) {
      $data["name_ar"]= $request->input()["name_ar"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $genders->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function settings_genders_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = genders::select(    
                  "genders.id   AS  id",
                  "genders.name_en   AS  name_en",
                  "genders.name_ar   AS  name_ar"
                   )
                   ;

  if($request->exists("id")){  
     $data=$data->where("genders.id","=" ,$request->input("id"));
  }
  if($request->exists("name_en")){  
     $data=$data->where("genders.name_en","=" ,$request->input("name_en"));
  }
  if($request->exists("name_ar")){  
     $data=$data->where("genders.name_ar","=" ,$request->input("name_ar"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function settings_genders_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table genders
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="genders";
 $id_name =  "genders_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End genders*****************************/

/*************Start Table status Api******************/
public function settings_status_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table status
 Parameters{
 name_en
 name_ar
 }
*/
   $request->validate(status::rules());;
   $data=array(); 
   $data["name_en"]=  $request->input()["name_en"] ; 
   $data["name_ar"]=  $request->input()["name_ar"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = status::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function settings_status_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table status
 Parameters{
 name_en
 name_ar
 }
*/
  // proccess 10000002
    try {
    $status = status::findOrFail($request->input()["id"]);
    //$request->validate(status::rules());;
    $data = array();
    if ($request->exists("name_en")) {
      $data["name_en"]= $request->input()["name_en"] ; 
    }
    if ($request->exists("name_ar")) {
      $data["name_ar"]= $request->input()["name_ar"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $status->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function settings_status_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = status::select(    
                  "status.id   AS  id",
                  "status.name_en   AS  name_en",
                  "status.name_ar   AS  name_ar"
                   )
                   ;

  if($request->exists("id")){  
     $data=$data->where("status.id","=" ,$request->input("id"));
  }
  if($request->exists("name_en")){  
     $data=$data->where("status.name_en","=" ,$request->input("name_en"));
  }
  if($request->exists("name_ar")){  
     $data=$data->where("status.name_ar","=" ,$request->input("name_ar"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function settings_status_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table status
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="status";
 $id_name =  "status_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End status*****************************/

/*************Start Table university_major Api******************/
public function settings_university_major_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table university_major
 Parameters{
 name_en
 name_ar
 }
*/
   $request->validate(university_major::rules());;
   $data=array(); 
   $data["name_en"]=  $request->input()["name_en"] ; 
   $data["name_ar"]=  $request->input()["name_ar"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = university_major::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function settings_university_major_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table university_major
 Parameters{
 name_en
 name_ar
 }
*/
  // proccess 10000002
    try {
    $university_major = university_major::findOrFail($request->input()["id"]);
    //$request->validate(university_major::rules());;
    $data = array();
    if ($request->exists("name_en")) {
      $data["name_en"]= $request->input()["name_en"] ; 
    }
    if ($request->exists("name_ar")) {
      $data["name_ar"]= $request->input()["name_ar"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $university_major->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function settings_university_major_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = university_major::select(    
                  "university_major.id   AS  id",
                  "university_major.name_en   AS  name_en",
                  "university_major.name_ar   AS  name_ar"
                   )
                   ;

  if($request->exists("id")){  
     $data=$data->where("university_major.id","=" ,$request->input("id"));
  }
  if($request->exists("name_en")){  
     $data=$data->where("university_major.name_en","=" ,$request->input("name_en"));
  }
  if($request->exists("name_ar")){  
     $data=$data->where("university_major.name_ar","=" ,$request->input("name_ar"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function settings_university_major_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table university_major
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="university_major";
 $id_name =  "university_major_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End university_major*****************************/

/*************Start Table city Api******************/
public function settings_city_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table city
 Parameters{
 name_en
 name_ar
 }
*/
   $request->validate(city::rules());;
   $data=array(); 
   $data["name_en"]=  $request->input()["name_en"] ; 
   $data["name_ar"]=  $request->input()["name_ar"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = city::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function settings_city_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table city
 Parameters{
 name_en
 name_ar
 }
*/
  // proccess 10000002
    try {
    $city = city::findOrFail($request->input()["id"]);
    //$request->validate(city::rules());;
    $data = array();
    if ($request->exists("name_en")) {
      $data["name_en"]= $request->input()["name_en"] ; 
    }
    if ($request->exists("name_ar")) {
      $data["name_ar"]= $request->input()["name_ar"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $city->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function settings_city_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = city::select(    
                  "city.id   AS  id",
                  "city.name_en   AS  name_en",
                  "city.name_ar   AS  name_ar"
                   )
                   ;

  if($request->exists("id")){  
     $data=$data->where("city.id","=" ,$request->input("id"));
  }
  if($request->exists("name_en")){  
     $data=$data->where("city.name_en","=" ,$request->input("name_en"));
  }
  if($request->exists("name_ar")){  
     $data=$data->where("city.name_ar","=" ,$request->input("name_ar"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function settings_city_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table city
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="city";
 $id_name =  "city_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End city*****************************/

/*************Start Table hospitals Api******************/
public function settings_hospitals_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table hospitals
 Parameters{
 name
 phone
 email
 city_id
 }
*/
   $request->validate(hospitals::rules());;
   $data=array(); 
   $data["name"]=  $request->input()["name"] ; 
   $data["phone"]=  $request->input()["phone"] ; 
   $data["email"]=  $request->input()["email"] ; 
   $data["city_id"]=  $request->input()["city_id"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = hospitals::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function settings_hospitals_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table hospitals
 Parameters{
 name
 phone
 email
 city_id
 }
*/
  // proccess 10000002
    try {
    $hospitals = hospitals::findOrFail($request->input()["id"]);
    //$request->validate(hospitals::rules());;
    $data = array();
    if ($request->exists("name")) {
      $data["name"]= $request->input()["name"] ; 
    }
    if ($request->exists("phone")) {
      $data["phone"]= $request->input()["phone"] ; 
    }
    if ($request->exists("email")) {
      $data["email"]= $request->input()["email"] ; 
    }
    if ($request->exists("city_id")) {
      $data["city_id"]= $request->input()["city_id"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $hospitals->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function settings_hospitals_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = hospitals::select(    
                  "hospitals.id   AS  id",
                  "hospitals.name   AS  name",
                  "hospitals.phone   AS  phone",
                  "hospitals.email   AS  email",
                  "city.name_$lang    AS  city_id_name_en",
                  "hospitals.city_id   AS  city_id"
                   )
                 ->join ( 'city as city' ,'hospitals.city_id', '=', 'city.id'  )
                   ;

  if($request->exists("id")){  
     $data=$data->where("hospitals.id","=" ,$request->input("id"));
  }
  if($request->exists("name")){  
     $data=$data->where("hospitals.name","=" ,$request->input("name"));
  }
  if($request->exists("phone")){  
     $data=$data->where("hospitals.phone","=" ,$request->input("phone"));
  }
  if($request->exists("email")){  
     $data=$data->where("hospitals.email","=" ,$request->input("email"));
  }
  if($request->exists("city_id")){  
     $data=$data->where("hospitals.city_id","=" ,$request->input("city_id"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function settings_hospitals_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table hospitals
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="hospitals";
 $id_name =  "hospitals_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End hospitals*****************************/

/*************Start Table specialties Api******************/
public function settings_specialties_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table specialties
 Parameters{
 name_en
 name_ar
 }
*/
   $request->validate(specialties::rules());;
   $data=array(); 
   $data["name_en"]=  $request->input()["name_en"] ; 
   $data["name_ar"]=  $request->input()["name_ar"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = specialties::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function settings_specialties_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table specialties
 Parameters{
 name_en
 name_ar
 }
*/
  // proccess 10000002
    try {
    $specialties = specialties::findOrFail($request->input()["id"]);
    //$request->validate(specialties::rules());;
    $data = array();
    if ($request->exists("name_en")) {
      $data["name_en"]= $request->input()["name_en"] ; 
    }
    if ($request->exists("name_ar")) {
      $data["name_ar"]= $request->input()["name_ar"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $specialties->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function settings_specialties_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = specialties::select(    
                  "specialties.id   AS  id",
                  "specialties.name_en   AS  name_en",
                  "specialties.name_ar   AS  name_ar"
                   )
                   ;

  if($request->exists("id")){  
     $data=$data->where("specialties.id","=" ,$request->input("id"));
  }
  if($request->exists("name_en")){  
     $data=$data->where("specialties.name_en","=" ,$request->input("name_en"));
  }
  if($request->exists("name_ar")){  
     $data=$data->where("specialties.name_ar","=" ,$request->input("name_ar"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function settings_specialties_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table specialties
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="specialties";
 $id_name =  "specialties_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End specialties*****************************/

/*************Start Table hospitals_has_specialties Api******************/
public function settings_hospitals_has_specialties_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table hospitals_has_specialties
 Parameters{
 specialties_id
 hospitals_id
 }
*/
   $request->validate(hospitals_has_specialties::rules());;
   $data=array(); 
   $data["specialties_id"]=  $request->input()["specialties_id"] ; 
   $data["hospitals_id"]=  $request->input()["hospitals_id"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = hospitals_has_specialties::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function settings_hospitals_has_specialties_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table hospitals_has_specialties
 Parameters{
 specialties_id
 hospitals_id
 }
*/
  // proccess 10000002
    try {
    $hospitals_has_specialties = hospitals_has_specialties::findOrFail($request->input()["id"]);
    //$request->validate(hospitals_has_specialties::rules());;
    $data = array();
    if ($request->exists("specialties_id")) {
      $data["specialties_id"]= $request->input()["specialties_id"] ; 
    }
    if ($request->exists("hospitals_id")) {
      $data["hospitals_id"]= $request->input()["hospitals_id"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $hospitals_has_specialties->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function settings_hospitals_has_specialties_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = hospitals_has_specialties::select(    
                  "hospitals_has_specialties.id   AS  id",
                  "specialties.name_$lang    AS  specialties_id_name_en",
                  "hospitals_has_specialties.specialties_id   AS  specialties_id",
                  "hospitals.name    AS  hospitals_id_name",
                  "hospitals_has_specialties.hospitals_id   AS  hospitals_id"
                   )
                 ->join ( 'specialties as specialties' ,'hospitals_has_specialties.specialties_id', '=', 'specialties.id'  )
                 ->join ( 'hospitals as hospitals' ,'hospitals_has_specialties.hospitals_id', '=', 'hospitals.id'  )
                   ;

  if($request->exists("id")){  
     $data=$data->where("hospitals_has_specialties.id","=" ,$request->input("id"));
  }
  if($request->exists("specialties_id")){  
     $data=$data->where("hospitals_has_specialties.specialties_id","=" ,$request->input("specialties_id"));
  }
  if($request->exists("hospitals_id")){  
     $data=$data->where("hospitals_has_specialties.hospitals_id","=" ,$request->input("hospitals_id"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function settings_hospitals_has_specialties_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table hospitals_has_specialties
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="hospitals_has_specialties";
 $id_name =  "hospitals_has_specialties_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End hospitals_has_specialties*****************************/

/*************Start Table clinical_setting Api******************/
public function settings_clinical_setting_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table clinical_setting
 Parameters{
 name
 }
*/
   $request->validate(clinical_setting::rules());;
   $data=array(); 
   $data["name"]=  $request->input()["name"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = clinical_setting::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function settings_clinical_setting_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table clinical_setting
 Parameters{
 name
 }
*/
  // proccess 10000002
    try {
    $clinical_setting = clinical_setting::findOrFail($request->input()["id"]);
    //$request->validate(clinical_setting::rules());;
    $data = array();
    if ($request->exists("name")) {
      $data["name"]= $request->input()["name"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $clinical_setting->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function settings_clinical_setting_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = clinical_setting::select(    
                  "clinical_setting.id   AS  id",
                  "clinical_setting.name   AS  name"
                   )
                   ;

  if($request->exists("id")){  
     $data=$data->where("clinical_setting.id","=" ,$request->input("id"));
  }
  if($request->exists("name")){  
     $data=$data->where("clinical_setting.name","=" ,$request->input("name"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function settings_clinical_setting_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table clinical_setting
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="clinical_setting";
 $id_name =  "clinical_setting_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End clinical_setting*****************************/

/*************Start Table monthly_evaluation_forms Api******************/
public function settings_monthly_evaluation_forms_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table monthly_evaluation_forms
 Parameters{
 name
 }
*/
   $request->validate(monthly_evaluation_forms::rules());;
   $data=array(); 
   $data["name"]=  $request->input()["name"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = monthly_evaluation_forms::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function settings_monthly_evaluation_forms_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table monthly_evaluation_forms
 Parameters{
 name
 }
*/
  // proccess 10000002
    try {
    $monthly_evaluation_forms = monthly_evaluation_forms::findOrFail($request->input()["id"]);
    //$request->validate(monthly_evaluation_forms::rules());;
    $data = array();
    if ($request->exists("name")) {
      $data["name"]= $request->input()["name"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $monthly_evaluation_forms->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function settings_monthly_evaluation_forms_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = monthly_evaluation_forms::select(    
                  "monthly_evaluation_forms.id   AS  id",
                  "monthly_evaluation_forms.name   AS  name"
                   )
                   ;

  if($request->exists("id")){  
     $data=$data->where("monthly_evaluation_forms.id","=" ,$request->input("id"));
  }
  if($request->exists("name")){  
     $data=$data->where("monthly_evaluation_forms.name","=" ,$request->input("name"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function settings_monthly_evaluation_forms_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table monthly_evaluation_forms
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="monthly_evaluation_forms";
 $id_name =  "monthly_evaluation_forms_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End monthly_evaluation_forms*****************************/

/*************Start Table assessment_criteria Api******************/
public function settings_assessment_criteria_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table assessment_criteria
 Parameters{
 monthly_evaluation_forms_id
 question
 }
*/
   $request->validate(assessment_criteria::rules());;
   $data=array(); 
   $data["monthly_evaluation_forms_id"]=  $request->input()["monthly_evaluation_forms_id"] ; 
   $data["question"]=  $request->input()["question"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = assessment_criteria::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function settings_assessment_criteria_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table assessment_criteria
 Parameters{
 monthly_evaluation_forms_id
 question
 }
*/
  // proccess 10000002
    try {
    $assessment_criteria = assessment_criteria::findOrFail($request->input()["id"]);
    //$request->validate(assessment_criteria::rules());;
    $data = array();
    if ($request->exists("monthly_evaluation_forms_id")) {
      $data["monthly_evaluation_forms_id"]= $request->input()["monthly_evaluation_forms_id"] ; 
    }
    if ($request->exists("question")) {
      $data["question"]= $request->input()["question"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $assessment_criteria->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function settings_assessment_criteria_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = assessment_criteria::select(    
                  "assessment_criteria.id   AS  id",
                  "monthly_evaluation_forms.name    AS  monthly_evaluation_forms_id_name",
                  "assessment_criteria.monthly_evaluation_forms_id   AS  monthly_evaluation_forms_id",
                  "assessment_criteria.question   AS  question"
                   )
                 ->join ( 'monthly_evaluation_forms as monthly_evaluation_forms' ,'assessment_criteria.monthly_evaluation_forms_id', '=', 'monthly_evaluation_forms.id'  )
                   ;

  if($request->exists("id")){  
     $data=$data->where("assessment_criteria.id","=" ,$request->input("id"));
  }
  if($request->exists("monthly_evaluation_forms_id")){  
     $data=$data->where("assessment_criteria.monthly_evaluation_forms_id","=" ,$request->input("monthly_evaluation_forms_id"));
  }
  if($request->exists("question")){  
     $data=$data->where("assessment_criteria.question","=" ,$request->input("question"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function settings_assessment_criteria_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table assessment_criteria
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="assessment_criteria";
 $id_name =  "assessment_criteria_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End assessment_criteria*****************************/

}
