<?php
namespace App\Http\Controllers\ApiController;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Response;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\SystemController\Delete;
use App\Http\Controllers\AdminController\UserAuthController;
use Illuminate\Support\Facades\Storage;

use App\Models\Admin\country_model as country;
use App\Models\Admin\city_model as city;
 
 
 /******************************************************/
 /******************************************************/
 /**********************Generated By *******************/
 /************* https://generatesystems.com ************/
 /******************************************************/
 /******************************************************/
 
 
class Apisetting  extends Controller{
/*************Start Table country Api******************/
public function setting_country_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table country
 Parameters{
 name_en
 name_ar
 }
*/
   $request->validate(country::rules());;
   $data=array(); 
   $data["name_en"]=  $request->input()["name_en"] ; 
   $data["name_ar"]=  $request->input()["name_ar"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = country::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function setting_country_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table country
 Parameters{
 name_en
 name_ar
 }
*/
  // proccess 10000002
    try {
    $country = country::findOrFail($request->input()["id"]);
    //$request->validate(country::rules());;
    $data = array();
    if ($request->exists("name_en")) {
      $data["name_en"]= $request->input()["name_en"] ; 
    }
    if ($request->exists("name_ar")) {
      $data["name_ar"]= $request->input()["name_ar"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $country->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function setting_country_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = country::select(    
                  "country.id   AS  id",
                  "country.name_en   AS  name_en",
                  "country.name_ar   AS  name_ar"
                   )
                   ;

  if($request->exists("id")){  
     $data=$data->where("country.id","=" ,$request->input("id"));
  }
  if($request->exists("name_en")){  
     $data=$data->where("country.name_en","=" ,$request->input("name_en"));
  }
  if($request->exists("name_ar")){  
     $data=$data->where("country.name_ar","=" ,$request->input("name_ar"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function setting_country_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table country
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="country";
 $id_name =  "country_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End country*****************************/

/*************Start Table city Api******************/
public function setting_city_insert(Request $request){
 // API PROCCESS 20000001
/*
 This function used to insert one row to table city
 Parameters{
 country_id
 name_en
 name_ar
 }
*/
   $request->validate(city::rules());;
   $data=array(); 
   $data["country_id"]=  $request->input()["country_id"] ; 
   $data["name_en"]=  $request->input()["name_en"] ; 
   $data["name_ar"]=  $request->input()["name_ar"] ; 
   $data["created_by"]=Auth::user()["id"];
   try {
       $insert = city::create($data);
   
       if ($insert) {
           return response()->json(["response" => "inserted"], 201); // HTTP 201 Created
       } else {
           return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
       }
      } catch (\Exception $e) {
         return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
     }
}


public function setting_city_update(Request $request){
 // API PROCCESS 20000002
/*
 This function used to update one row from table city
 Parameters{
 country_id
 name_en
 name_ar
 }
*/
  // proccess 10000002
    try {
    $city = city::findOrFail($request->input()["id"]);
    //$request->validate(city::rules());;
    $data = array();
    if ($request->exists("country_id")) {
      $data["country_id"]= $request->input()["country_id"] ; 
    }
    if ($request->exists("name_en")) {
      $data["name_en"]= $request->input()["name_en"] ; 
    }
    if ($request->exists("name_ar")) {
      $data["name_ar"]= $request->input()["name_ar"] ; 
    }
      $data["updated_by"]=Auth::user()["id"];
      $data["updated_at"]= now();
      $updated = $city->update($data);  
    if($updated){ 
      return response()->json(["response" => "updated"], 200); // HTTP 200 OK
    }else{
      return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error 
    }
    } catch (\Exception $e) {
      return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
    }
}

public function setting_city_viewAll(Request $request){
 // API PROCCESS 20000007
$lang = $request->hasHeader("Accept-Language") ? $request->header("Accept-Language") : "en"; 
$host = request()->getHttpHost(); 
$hostUrl = "https://".$host."/uploads/"; 
$data = city::select(    
                  "city.id   AS  id",
                  "country.name_$lang    AS  country_id_name_en",
                  "city.country_id   AS  country_id",
                  "city.name_en   AS  name_en",
                  "city.name_ar   AS  name_ar"
                   )
                 ->join ( 'country as country' ,'city.country_id', '=', 'country.id'  )
                   ;

  if($request->exists("id")){  
     $data=$data->where("city.id","=" ,$request->input("id"));
  }
  if($request->exists("country_id")){  
     $data=$data->where("city.country_id","=" ,$request->input("country_id"));
  }
  if($request->exists("name_en")){  
     $data=$data->where("city.name_en","=" ,$request->input("name_en"));
  }
  if($request->exists("name_ar")){  
     $data=$data->where("city.name_ar","=" ,$request->input("name_ar"));
  }
 $data = $data->paginate(15);
 $countRows = $data->total();
 if($countRows >= 1){
 return response([
       "status"=>"found_data",
       "data"=>$data,
       ],200);
 }else{
 return response([
       "status"=>"not_found_data",
       "data"=>"",
       ],400);
 }           
}


public function setting_city_delete(Request $request){
 // API PROCCESS 20000003
/*
 This function used to remove row from table city
 Parameters :{
 id 
 }
*/
 $id=$request->input("id");
 $table="city";
 $id_name =  "city_id";
        try {
            // Check if the row can be deleted
            if (Delete::checkRow($id_name, $id)) {
                return response()->json(["response" => "not_allow"], 403); // HTTP 403 Forbidden
            }
        
            // Attempt to delete the row
            $deleted = DB::table($table)->where("id", $id)->delete();
            if ($deleted) {
                return response()->json(["response" => "deleted"], 200); // HTTP 200 OK
            } else {
                return response()->json(["response" => "not_found"], 404); // HTTP 404 Not Found
            }
        } catch (\Exception $e) {
            return response()->json(["response" => "error"], 500); // HTTP 500 Internal Server Error
        }
}
/************************End city*****************************/

}
